# Generated by Django 3.1 on 2022-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=1)),
                ('school', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('grades', models.DateTimeField(auto_now_add=True)),
                ('scores', models.TextField(null=True)),
                ('stud_t_ratio', models.TextField(null=True)),
                ('review', models.TextField(null=True)),
                ('district', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
