# Generated by Django 3.1 on 2022-08-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultlog',
            name='scores',
        ),
    ]
