# Generated by Django 3.1 on 2022-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolratings', '0002_remove_resultlog_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultlog',
            name='total_students',
            field=models.FloatField(default=1),
        ),
    ]
