# Generated by Django 3.1 on 2022-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolratings', '0004_auto_20220816_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultlog',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
