# Generated by Django 3.1 on 2022-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolratings', '0006_auto_20220825_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultlog',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
